### ISSUE TITLE
mac_address.py needs a refactor

### ISSUE THREAD

**Issue by clburlison** [chilcote/unearth#2]
Kind of a module. Kind of a pick what you want project.

As such `mac_address.py` needs to be refactored to not depend on a separate file. Example if I call it directly I get "The"

```bash
 ~/D/unearth  ± python /usr/local/munki/conditions/facts/mac_address.py 
<result>The</result>
```

**Comment by clburlison** [comment]
Forgot the huge thank you! Very useful data included in unearth. If you agree I can make a PR for this later.

**Comment by chilcote** [comment]
Oh.  Right, I thought I got rid of all those "external fact" things.  That was a holdover from an earlier attempt.  I'll clean that up.

I'm not sure what you're doing there with the munki facts, but I'm sure it's really clever and I would like to subscribe to your periodical.
